#################################################################
#  _____ _      _                    _                 _        #
# |  __ (_)    | |                  | |               (_)       #
# | |__) |  ___| |_ _   _ _ __ ___  | |     ___   __ _ _ _ __   #
# |  ___/ |/ __| __| | | | '__/ _ \ | |    / _ \ / _` | | '_ \  #
# | |   | | (__| |_| |_| | | |  __/ | |___| (_) | (_| | | | | | #
# |_|   |_|\___|\__|\__,_|_|  \___| |______\___/ \__, |_|_| |_| #
#                                                 __/ |         #
#                                                |___/          #
#################################################################

#############
# Messsages
########
# Each message is a line, leave blank for a blank line
# (If image height is 8, you can have eight lines; etc.)
# Chat codes supported.
########
# Variables:
# %pname%       - Joined player's name (no formatting)
# %online%      - Players online
# %max%         - Maximum players
# %motd%        - MOTD
# %displayname% - Joined player's display name

messages:
    - ''
    - '&5Welcome to &dGeneric Server Name&5!'
    - ''
    - '&7» [&e%online%&7/&e%max%&7] player(s) online.'
    - '&7» &aNEW: &7Feature X added!'
    - ''
    - '&7» &aPictureLogin &7by &aNathanG&7.'
    - ''

#############
# First Join Message
########
# Set to true to send a different messsage
# when a player joins for the first
# time. Refer to above for variables.

show-first-join: true

first-join-messages:
    - ''
    - '&5Welcome to &dGeneric Server Name&5!'
    - ''
    - '&7» [&e%online%&7/&e%max%&7] player(s) online.'
    - '&7» &aNEW: &7Feature X added!'
    - ''
    - '&7Please welcome &a%pname% &7to the server!'
    - ''

#############
# Leave Messages
########
# Set to true to send a
# message whenever a player
# leaves the server. Refer
# to top for variables.

show-leave-message: false

leave-messages:
    - ''
    - '&5Welcome to &dGeneric Server Name&5!'
    - ''
    - '&7» [&e%online%&7/&e%max%&7] player(s) online.'
    - '&7» &aNEW: &7Feature X added!'
    - ''
    - '&7» &aPictureLogin &7by &aNathanG&7.'
    - ''

#############
# Clear Chat
########
# Set to true to clear the chat
# before the message is sent.
# Acceptable: [true|false]

clear-chat: false

#############
# Center Text
########
# Whether or not to center
# the text beside the image.
# Acceptable: [true|false]

center-text: false

#############
# Block join / leave messages
########
# Set to true to block
# the default login
# and logout messages.

block-join-message: false
block-leave-message: false

#############
# Show to player only
########
# Set to true to only send
# the login message to
# the player that joins.

player-only: true

#############
# Image Character
######## 
# Change this to change what
# character the image is made of.
########
# Acceptable:
# - BLOCK
# - DARK_SHADE
# - MEDIUM_SHADE
# - LIGHT_SHADE

character: 'BLOCK'

#############
# URL
######## 
# Where to get the picture from.
# By default it uses crafatar.
# You should probably leave this where it is.
########
# Variables:
# %pname%  - Joined player's name
# %uuid%   - Joined player's UUID

url: 'https://crafatar.com/avatars/%uuid%.png?size=8&overlay&default=MHF_Steve'

#############
# Metrics
########
# Allow this plugin to send anonymous metrics
# to bStats? https://bstats.org/
# Set to false to disable.
metrics: true