name: PictureLogin
main: me.itsnathang.picturelogin.PictureLogin
author: NathanG
version: ${version}
commands:
  picturelogin:
    description: Picture Login command.
permisions:
  picturelogin.main:
    default: op
    description: Allows you to use /picturelogin
  picturelogin.show:
    default: op
    description: Allows message to be shown
    