name: PictureLogin
main: PictureLogin
author: NathanG
version: 1.1
commands:
  picturelogin:
    description: Picture Login command.
permisions:
  picturelogin.main:
    default: op
    description: Allows you to use /picturelogin
  picturelogin.show:
    default: op
    description: Allows message to be shown
    